### PR TITLE
Fix the shell's "retry job" and "cancel job" actions

### LINKED ISSUE #331: Raise an error when finish_job is called on a job whose status is not "doing"
The SQL query used by `JobStore.finish_job` increments the job's `attempts` value. So this method shouldn't be called on jobs whose current status is not `doing`, and we probably want to raise an error when the job doesn't have the status `doing`. We may even want to enforce the at this SQL level.

### PR DESCRIPTION
**Pull request by elemoine**
This PR provides a number of things:

* Change the `procrastinate_finish_job` SQL function to raise an error when the job status is not "todo" or "doing" (#331).
* Change the `procrastinate_retry_job` SQL function to raise an error when the job status is not "doing"
* Change the shell's `retry job` and `cancel job` actions to rely on the above functions (#330).

Closes #331 #330

### Successful PR Checklist:

- [x] Tests
  - [ ] (not applicable?)
- [ ] Documentation
  - [x] (not applicable?)
- [x] Had a good time contributing?

### CODE REVIEW

**Comment by elemoine** [comment]
This is ready for review!

Note to self: review the migrations before merging.

File: procrastinate/sql/schema.sql [hunk 1]
```diff
@@ -203,14 +203,29 @@ $$;
 CREATE FUNCTION procrastinate_finish_job(job_id integer, end_status procrastinate_job_status, delete_job boolean) RETURNS void
     LANGUAGE plpgsql
 AS $$
+DECLARE
+    _job_id bigint;
 BEGIN
+    IF end_status NOT IN ('succeeded', 'failed') THEN
+        RAISE 'End status should be either "succeeded" or "failed"';
```
Comment (elemoine) [inline procrastinate/sql/schema.sql:210]: Add job id.

```
RAISE 'End status should be either "succeeded" or "failed" (job id: %)', job_id
```

File: procrastinate/sql/schema.sql [hunk 2]
```diff
@@ -203,14 +203,29 @@ $$;
...
+            attempts =
+                CASE
+                    WHEN status = 'doing' THEN attempts + 1
+                    ELSE attempts
+                END
+        WHERE id = job_id AND status IN ('todo', 'doing')
+        RETURNING id INTO _job_id;
+    END IF;
+    IF _job_id IS NULL THEN
+        RAISE 'Job with id % was not found or not in "doing" or "todo" status', job_id;
```
Comment (elemoine) [inline procrastinate/sql/schema.sql:228]:
```
RAISE 'Job was not found or not in "doing" or "todo" status (job id: %)', job_id;
```

File: tests/integration/test_manager.py [hunk 3]
```diff
@@ -242,17 +242,66 @@ async def test_finish_job(get_all, pg_job_manager, job_factory):
...
 
 
-async def test_finish_job_retry(get_all, pg_job_manager, job_factory):
+async def test_finish_job_status_error(get_all, pg_job_manager, job_factory):
+    job = job_factory(queue="queue_a")
+    await pg_job_manager.defer_job_async(job)
+
+    job_rows = await get_all("procrastinate_jobs", "id", "status")
+    assert len(job_rows) == 1
+    assert job_rows[0]["status"] == "todo"
```
Comment (elemoine) [inline tests/integration/test_manager.py:254]: Can be removed.

File: tests/integration/test_manager.py [hunk 4]
```diff
@@ -242,17 +242,66 @@ async def test_finish_job(get_all, pg_job_manager, job_factory):
...
+
+    job_id = job_rows[0]["id"]
+    job = job.evolve(id=job_id)
+
+    await pg_job_manager.finish_job(
+        job=job, status=jobs.Status.FAILED, delete_job=False
+    )
+    job_rows = await get_all("procrastinate_jobs", "status", "attempts")
+    assert job_rows == [{"status": "failed", "attempts": 0}]
```
Comment (elemoine) [inline tests/integration/test_manager.py:263]: We could add local fixtures `deferred_job` and `failed_job`.

File: tests/integration/test_manager.py [hunk 5]
```diff
@@ -242,17 +242,66 @@ async def test_finish_job(get_all, pg_job_manager, job_factory):
...
+async def test_finish_job_bad_end_status(get_all, pg_job_manager, job_factory):
+    job = job_factory(queue="queue_a")
+    await pg_job_manager.defer_job_async(job)
+
+    job_rows = await get_all("procrastinate_jobs", "id", "status")
+    assert len(job_rows) == 1
+    assert job_rows[0]["status"] == "todo"
+
+    job_id = job_rows[0]["id"]
+    job = job.evolve(id=job_id)
```
Comment (elemoine) [inline tests/integration/test_manager.py:296]: Use the `deferred_job` fixture.

File: tests/integration/test_manager.py [hunk 6]
```diff
@@ -242,17 +242,66 @@ async def test_finish_job(get_all, pg_job_manager, job_factory):
...
+        job=job, status=jobs.Status.FAILED, delete_job=False
+    )
+    job_rows = await get_all("procrastinate_jobs", "status", "attempts")
+    assert job_rows == [{"status": "failed", "attempts": 0}]
+
+    with pytest.raises(exceptions.ConnectorException) as excinfo:
+        await pg_job_manager.finish_job(
+            job=job, status=jobs.Status.FAILED, delete_job=False
+        )
+    assert isinstance(excinfo.value.__cause__, psycopg2.errors.RaiseException)
```
Comment (elemoine) [inline tests/integration/test_manager.py:269]: To remove.

File: tests/integration/test_manager.py [hunk 7]
```diff
@@ -242,17 +242,66 @@ async def test_finish_job(get_all, pg_job_manager, job_factory):
...
+    assert job_rows[0]["status"] == "todo"
+
+    job_id = job_rows[0]["id"]
+    job = job.evolve(id=job_id)
+
+    with pytest.raises(exceptions.ConnectorException) as excinfo:
+        await pg_job_manager.finish_job(
+            job=job, status=jobs.Status.TODO, delete_job=False
+        )
+    assert isinstance(excinfo.value.__cause__, psycopg2.errors.RaiseException)
```
Comment (elemoine) [inline tests/integration/test_manager.py:302]: To remove.

File: procrastinate/manager.py [hunk 8]
```diff
@@ -417,31 +433,49 @@ async def list_tasks_async(
             )
         ]
 
-    async def set_job_status_async(self, id: int, status: str) -> Dict[str, Any]:
+    async def retry_job_return_info_async(self, job_id: int) -> Dict[str, Any]:
```
Comment (elemoine) [inline procrastinate/manager.py:436]: Remove that function, and call `retry_job_by_id` and `list_job_async` directly.

Comment (elemoine) [reply procrastinate/manager.py:436]: Related idea: change `list_jobs_async` to return a list of Job objects.

File: procrastinate/sql/schema.sql [hunk 9]
```diff
@@ -233,12 +233,18 @@ $$;
...
 BEGIN
     UPDATE procrastinate_jobs
     SET status = 'todo',
         attempts = attempts + 1,
         scheduled_at = retry_at
-    WHERE id = job_id;
+    WHERE id = job_id AND status = 'doing'
+    RETURNING id INTO _job_id;
+    IF _job_id IS NULL THEN
+        RAISE 'Job with id % was not found or not in "doing" status', job_id;
```
Comment (elemoine) [inline procrastinate/sql/schema.sql:246]: Change raise message.

File: procrastinate/jobs.py [hunk 10]
```diff
@@ -87,6 +91,9 @@ def from_row(cls, row: Dict[str, Any]) -> "Job":
             attempts=row["attempts"],
         )
 
+    def asdict(self) -> types.JSONDict:
+        return attr.asdict(self)
+
     def log_context(self) -> types.JSONDict:
         context = attr.asdict(self)
```
Comment (ewjoachim) [inline procrastinate/jobs.py:98]: Well then, let's use asdict :)

Comment (elemoine) [reply procrastinate/jobs.py]: Yep, done.

Comment (elemoine) [reply procrastinate/jobs.py]: Argh, that actually causes mypy errors:

```
procrastinate/jobs.py:101: error: Item "str" of "Union[str, int, float, bool, None, Dict[str, Any], List[Any]]" has no attribute "isoformat"
procrastinate/jobs.py:101: error: Item "int" of "Union[str, int, float, bool, None, Dict[str, Any], List[Any]]" has no attribute "isoformat"
procrastinate/jobs.py:101: error: Item "float" of "Union[str, int, float, bool, None, Dict[str, Any], List[Any]]" has no attribute "isoformat"
procrastinate/jobs.py:101: error: Item "bool" of "Union[str, int, float, bool, None, Dict[str, Any], List[Any]]" has no attribute "isoformat"
procrastinate/jobs.py:101: error: Item "None" of "Union[str, int, float, bool, None, Dict[str, Any], List[Any]]" has no attribute "isoformat"
procrastinate/jobs.py:101: error: Item "Dict[str, Any]" of "Union[str, int, float, bool, None, Dict[str, Any], List[Any]]" has no attribute "isoformat"
procrastinate/jobs.py:101: error: Item "List[Any]" of "Union[str, int, float, bool, None, Dict[str, Any], List[Any]]" has no attribute "isoformat"
Found 7 errors in 1 file (checked 30 source files)
```

Comment (elemoine) [reply procrastinate/jobs.py:98]: I reverted the commit.

**Comment by elemoine** [comment]
Once merged, add a "breaking change" to the changelog, as `JobManager.defer_job` now returns a job object rather than a job id.

File: procrastinate/jobs.py [hunk 11]
```diff
@@ -47,6 +47,8 @@ class Job:
     ----------
     id :
         Internal id uniquely identifying the job.
+    status :
+        Status of the job.
```
Comment (ewjoachim) [inline procrastinate/jobs.py:51]: Oh, I didn't excpet we'd finally add that. I don't remember why we didn't model this at first. I'd say, because this is obvious when we defer jobs, and obvious when the worker treats them, so there was no use. Now with the shell and all the ways to get jobs in various states, it makes sense.

File: procrastinate/jobs.py (hunk 10 above)
Comment (ewjoachim) [reply procrastinate/jobs.py:98]: That's logical, I'll comment above.

File: procrastinate/jobs.py [hunk 12]
```diff
@@ -87,6 +91,9 @@ def from_row(cls, row: Dict[str, Any]) -> "Job":
             attempts=row["attempts"],
         )
 
+    def asdict(self) -> types.JSONDict:
```
Comment (ewjoachim) [inline procrastinate/jobs.py:94]: it's not a JSONDict, one of the values is a datetime. It's a `Dict`, and I'm not sure it's worth being more precise. `Dict[str, Any]` if you really want.

Comment (ewjoachim) [reply procrastinate/jobs.py]: (fixed it)

**Review by ewjoachim — APPROVED** [review]
